/*
 * Generated by Telosys ( https://www.telosys.org/ )
 * 2022-03-31 (18:10:46)
 */
package org.demo.orders.domain.service;

public interface DomainService {

    /**
     * Returns current domain model version
     * @return version
     */
    String getVersion() ;
}
