/*
 * Generated by Telosys ( https://www.telosys.org/ )
 * 2022-04-01 (00:02:09)
 */
package org.demo.orders.application.mapper;

import java.util.List; 
import org.mapstruct.Mapper;

import org.demo.orders.domain.model.Aaa;
import org.demo.orders.rest.dto.AaaRestDto;
/**
 * Mapper for entity "Aaa" 
 * Conversion from domain object to DTO 
 * 
 * @author Telosys
 */
@Mapper(componentModel = "spring", uses = { BbbMapper.class, CccMapper.class })
public interface AaaMapper {

	/**
	 * Converts the given domain object to DTO
	 * @param aaa object to convert
	 * @return
	 */	
	public AaaRestDto toDTO(Aaa aaa);
	
	/**
	 * Converts the given domain list to DTO list
	 * @param aaaList list to convert
	 * @return
	 */	
	public List<AaaRestDto> toDTOList(List<Aaa> aaaList);

}

