/*
 * Generated by Telosys ( https://www.telosys.org/ )
 * 2022-04-01 (00:02:09)
 */
package org.demo.orders.application.mapper;

import java.util.List; 
import org.mapstruct.Mapper;

import org.demo.orders.domain.model.Bbb;
import org.demo.orders.rest.dto.BbbRestDto;
/**
 * Mapper for entity "Bbb" 
 * Conversion from domain object to DTO 
 * 
 * @author Telosys
 */
@Mapper(componentModel = "spring", uses = { DddMapper.class, EeeMapper.class })
public interface BbbMapper {

	/**
	 * Converts the given domain object to DTO
	 * @param bbb object to convert
	 * @return
	 */	
	public BbbRestDto toDTO(Bbb bbb);
	
	/**
	 * Converts the given domain list to DTO list
	 * @param bbbList list to convert
	 * @return
	 */	
	public List<BbbRestDto> toDTOList(List<Bbb> bbbList);

}

