/*
 * Generated by Telosys ( https://www.telosys.org/ )
 * 2022-04-01 (00:02:09)
 */
package org.demo.orders.application.mapper;

import java.util.List; 
import org.mapstruct.Mapper;

import org.demo.orders.domain.model.Fff;
import org.demo.orders.rest.dto.FffRestDto;
/**
 * Mapper for entity "Fff" 
 * Conversion from domain object to DTO 
 * 
 * @author Telosys
 */
@Mapper(componentModel = "spring")
public interface FffMapper {

	/**
	 * Converts the given domain object to DTO
	 * @param fff object to convert
	 * @return
	 */	
	public FffRestDto toDTO(Fff fff);
	
	/**
	 * Converts the given domain list to DTO list
	 * @param fffList list to convert
	 * @return
	 */	
	public List<FffRestDto> toDTOList(List<Fff> fffList);

}

