/*
 * Generated by Telosys ( https://www.telosys.org/ )
 * 2022-04-01 (00:02:09)
 */
package org.demo.orders.application.mapper;

import java.util.List; 
import org.mapstruct.Mapper;

import org.demo.orders.domain.model.Foo;
import org.demo.orders.rest.dto.FooRestDto;
/**
 * Mapper for entity "Foo" 
 * Conversion from domain object to DTO 
 * 
 * @author Telosys
 */
@Mapper(componentModel = "spring")
public interface FooMapper {

	/**
	 * Converts the given domain object to DTO
	 * @param foo object to convert
	 * @return
	 */	
	public FooRestDto toDTO(Foo foo);
	
	/**
	 * Converts the given domain list to DTO list
	 * @param fooList list to convert
	 * @return
	 */	
	public List<FooRestDto> toDTOList(List<Foo> fooList);

}

