/*
 * Generated by Telosys ( https://www.telosys.org/ )
 * 2022-03-31 (23:44:54)
 */
package org.demo.orders.rest.dto;

import java.io.Serializable;

import java.util.List;

/**
 * REST DTO for entity "Bbb"
 * 
 * @author Telosys
 *
 */
public class BbbRestDto implements Serializable
{
    private static final long serialVersionUID = 1L;

    private Integer id; // ID
    private String name; 

    //--- Relationships
    private DddRestDto ddd ; 
    private List<EeeRestDto> eee ;

    /**
     * Default constructor
     */
    public BbbRestDto() {
        super();
    }
    
    /**
     * Set the "id" field value
     * @param id
     */
	public void setId( Integer id ) {
        this.id = id ;
    }
    /**
     * Get the "id" field value
     * @return the field value
     */
	public Integer getId() {
        return this.id;
    }

    /**
     * Set the "name" field value
     * @param name
     */
	public void setName( String name ) {
        this.name = name ;
    }
    /**
     * Get the "name" field value
     * @return the field value
     */
	public String getName() {
        return this.name;
    }


    //--- Relationships
    public DddRestDto getDdd() {
        return this.ddd;
    } 
    public void setDdd(DddRestDto ddd) {
        this.ddd = ddd;
    } 
	
    public List<EeeRestDto> getEee() {
        return this.eee;
    } 
    public void setEee(List<EeeRestDto> eee) {
        this.eee = eee;
    } 
	

    @Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(name);
        return sb.toString(); 
    } 

}
