/*
 * Generated by Telosys ( https://www.telosys.org/ )
 * 2022-03-31 (23:44:54)
 */
package org.demo.orders.rest.dto;

import java.io.Serializable;


/**
 * REST DTO for entity "Ddd"
 * 
 * @author Telosys
 *
 */
public class DddRestDto implements Serializable
{
    private static final long serialVersionUID = 1L;

    private Integer id; // ID
    private String name; 

    //--- Relationships
    private CccRestDto ccc ; 
    private FffRestDto fff ; 

    /**
     * Default constructor
     */
    public DddRestDto() {
        super();
    }
    
    /**
     * Set the "id" field value
     * @param id
     */
	public void setId( Integer id ) {
        this.id = id ;
    }
    /**
     * Get the "id" field value
     * @return the field value
     */
	public Integer getId() {
        return this.id;
    }

    /**
     * Set the "name" field value
     * @param name
     */
	public void setName( String name ) {
        this.name = name ;
    }
    /**
     * Get the "name" field value
     * @return the field value
     */
	public String getName() {
        return this.name;
    }


    //--- Relationships
    public CccRestDto getCcc() {
        return this.ccc;
    } 
    public void setCcc(CccRestDto ccc) {
        this.ccc = ccc;
    } 
	
    public FffRestDto getFff() {
        return this.fff;
    } 
    public void setFff(FffRestDto fff) {
        this.fff = fff;
    } 
	

    @Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(name);
        return sb.toString(); 
    } 

}
