/*
 * Generated by Telosys ( https://www.telosys.org/ )
 * 2022-03-31 (23:44:54)
 */
package org.demo.orders.rest.dto;

import java.io.Serializable;


/**
 * REST DTO for entity "Foo"
 * 
 * @author Telosys
 *
 */
public class FooRestDto implements Serializable
{
    private static final long serialVersionUID = 1L;

    private String code; // ID
    private Integer id; // ID
    private String firstName; 
    private String lastName; 


    /**
     * Default constructor
     */
    public FooRestDto() {
        super();
    }
    
    /**
     * Set the "code" field value
     * @param code
     */
	public void setCode( String code ) {
        this.code = code ;
    }
    /**
     * Get the "code" field value
     * @return the field value
     */
	public String getCode() {
        return this.code;
    }

    /**
     * Set the "id" field value
     * @param id
     */
	public void setId( Integer id ) {
        this.id = id ;
    }
    /**
     * Get the "id" field value
     * @return the field value
     */
	public Integer getId() {
        return this.id;
    }

    /**
     * Set the "firstName" field value
     * @param firstName
     */
	public void setFirstName( String firstName ) {
        this.firstName = firstName ;
    }
    /**
     * Get the "firstName" field value
     * @return the field value
     */
	public String getFirstName() {
        return this.firstName;
    }

    /**
     * Set the "lastName" field value
     * @param lastName
     */
	public void setLastName( String lastName ) {
        this.lastName = lastName ;
    }
    /**
     * Get the "lastName" field value
     * @return the field value
     */
	public String getLastName() {
        return this.lastName;
    }



    @Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(code);
        sb.append("|");
        sb.append(id);
        sb.append("|");
        sb.append(firstName);
        sb.append("|");
        sb.append(lastName);
        return sb.toString(); 
    } 

}
