/*
 * Generated by Telosys ( https://www.telosys.org/ )
 * 2022-04-01 (00:02:08)
 */

package org.demo.orders.application.exception;

import org.demo.orders.application.common.GenericException;

/**
 * Error code
 *
 * @author Telosys
 *
 */
public class AaaException extends GenericException {

    public AaaException(ErrorCode errorCode) {
        super(errorCode);
    }

    public AaaException(ErrorCode errorCode, Throwable cause) {
        super(errorCode, cause);
    }
}
