/*
 * Generated by Telosys ( https://www.telosys.org/ )
 * 2022-04-01 (00:02:09)
 */
package org.demo.orders.application.exception;

/**
 * Error code
 *
 * @author Telosys
 *
 */
public enum ErrorCode {

    DELETE_NOT_FOUND("Cannot delete - Not found");

    /** Error message. */
    private String message;

    /**
     * Gets error message.
     *
     * @return the message
     */
    public String getMessage() {
        return message;
    }

    /**
     * Instantiates a new error code.
     *
     * @param message error message
     */
    private ErrorCode(String message) {
        this.message = message;
    }
}
