/*
 * Generated by Telosys ( https://www.telosys.org/ )
 * 2022-03-31 (23:44:54)
 */
package org.demo.orders.rest.dto.response;

import org.demo.orders.rest.dto.common.AbstractRestResponse;
import org.demo.orders.rest.dto.BbbRestDto;

import java.util.List;

public class BbbRestResponse extends AbstractRestResponse<BbbRestDto> {

    /**
     * Constructor
     * @param list
     * @param totalElements
     * @param pageSize
     */
    public BbbRestResponse(List<BbbRestDto> list, long totalElements, int pageSize) {
        super(list, totalElements, pageSize);
    }
}