/*
 * Generated by Telosys ( https://www.telosys.org/ )
 * 2022-03-31 (18:10:46)
 */
package org.demo.orders.domain.model;

import org.demo.orders.domain.common.AggregateRoot;

/**
 * Domain parent abstract class for entity "Customer"
 *
 * @author Telosys
 *
 */
public abstract class CustomerParent extends AggregateRoot {

	private Integer id;
	private String firstName;
	private String lastName;


    private CustomerAddress address ;

	/**
	 * Default constructor with restricted visibility
	 * (supposed to be used only by descendant )
	 */
	CustomerParent() {
	}




    /**
     * Set the "id" attribute value (restricted visibility)
     * @param id
     */
	void setId( Integer id ) {
        this.id = id ;
    }
    /**
     * Get the "id" attribute value
     * @return the attribute value
     */
	public Integer getId() {
        return this.id;
    }

    /**
     * Set the "firstName" attribute value (restricted visibility)
     * @param firstName
     */
	void setFirstName( String firstName ) {
        this.firstName = firstName ;
    }
    /**
     * Get the "firstName" attribute value
     * @return the attribute value
     */
	public String getFirstName() {
        return this.firstName;
    }

    /**
     * Set the "lastName" attribute value (restricted visibility)
     * @param lastName
     */
	void setLastName( String lastName ) {
        this.lastName = lastName ;
    }
    /**
     * Get the "lastName" attribute value
     * @return the attribute value
     */
	public String getLastName() {
        return this.lastName;
    }



    //--- GETTERS FOR LINKS
    public CustomerAddress getAddress() {
        return this.address;
    } 


	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(firstName);
        sb.append("|");
        sb.append(lastName);
        return sb.toString(); 
    } 

}
