/*
 * Generated by Telosys ( https://www.telosys.org/ )
 * 2022-03-31 (18:10:46)
 */
package org.demo.orders.domain.model;


/**
 * Domain class for "Customer"
 *
 * @author Telosys
 *
 */
public final class Customer extends CustomerParent {


	/**
	 * Default constructor with restricted visibility
	 * (supposed to be used only by a Factory )
	 */
	Customer() {
		super();
	}

	/**
	 * Create aggregate business methods here...
	 */
	public void doSomethingWithThisAggregate() {
		// TODO
	}
}
