/*
 * Generated by Telosys ( https://www.telosys.org/ )
 * 2022-03-31 (23:44:54)
 */
package org.demo.orders.domain.model;

import java.util.ArrayList;
import java.util.List;
import org.demo.orders.rest.dto.CustomerRestDto;
import org.demo.orders.rest.dto.CustomerAddressRestDto;
/**
 * Domain factory for aggregate "Customer" based 
 * based on REST DTO input
 *
 * @author Telosys
 *
 */

//-----------------------------------
// referencedEntitiesForAllLevels : 
// - CustomerAddress 
//-----------------------------------
// 
public final class CustomerFactoryRestDto {


	/**
	 * Create a new instance of "Customer" from "Data Transfer Object"
	 * @param dto
	 * @return created instance
	 */

	public static Customer createCustomer(CustomerRestDto dto) {
		if (dto == null) {
			throw new IllegalArgumentException("CustomerRestDto is null");
		}
		Customer customer = new Customer();
		customer.setId(dto.getId());
		customer.setFirstName(dto.getFirstName());
		customer.setLastName(dto.getLastName());
		return customer;
	}

// - CustomerAddress 
	private static CustomerAddress createCustomerAddress(CustomerAddressRestDto dto) {
		if (dto == null) {
			throw new IllegalArgumentException("CustomerAddressRestDto is null");
		}
		CustomerAddress customerAddress = new CustomerAddress();
		customerAddress.setId(dto.getId());
		customerAddress.setStreet(dto.getStreet());
		customerAddress.setComplement(dto.getComplement());
		customerAddress.setZipCode(dto.getZipCode());
		customerAddress.setCity(dto.getCity());
		customerAddress.setState(dto.getState());
		customerAddress.setCustomerId(dto.getCustomerId());
		return customerAddress;
	}
	private static List<CustomerAddress> createCustomerAddressList(List<CustomerAddressRestDto> dtoList) {
		List<CustomerAddress> list = null;
		if (dtoList != null) {
			list = new ArrayList<CustomerAddress>();
			for ( CustomerAddressRestDto dto : dtoList ) {
				list.add(createCustomerAddress(dto));
			}
		}
		return list;
	}

}
