/*
 * Generated by Telosys ( https://www.telosys.org/ )
 * 2022-03-31 (18:10:46)
 */
package org.demo.orders.domain.model;

import org.demo.orders.domain.common.Entity;

/**
 * Domain parent abstract class for entity "CustomerAddress"
 *
 * @author Telosys
 *
 */
public abstract class CustomerAddressParent extends Entity {

	private int id;
	private String street;
	private String complement;
	private String zipCode;
	private String city;
	private String state;
	private Integer customerId;


	/**
	 * Default constructor with restricted visibility
	 * (supposed to be used only by descendant )
	 */
	CustomerAddressParent() {
	}




    /**
     * Set the "id" attribute value (restricted visibility)
     * @param id
     */
	void setId( int id ) {
        this.id = id ;
    }
    /**
     * Get the "id" attribute value
     * @return the attribute value
     */
	public int getId() {
        return this.id;
    }

    /**
     * Set the "street" attribute value (restricted visibility)
     * @param street
     */
	void setStreet( String street ) {
        this.street = street ;
    }
    /**
     * Get the "street" attribute value
     * @return the attribute value
     */
	public String getStreet() {
        return this.street;
    }

    /**
     * Set the "complement" attribute value (restricted visibility)
     * @param complement
     */
	void setComplement( String complement ) {
        this.complement = complement ;
    }
    /**
     * Get the "complement" attribute value
     * @return the attribute value
     */
	public String getComplement() {
        return this.complement;
    }

    /**
     * Set the "zipCode" attribute value (restricted visibility)
     * @param zipCode
     */
	void setZipCode( String zipCode ) {
        this.zipCode = zipCode ;
    }
    /**
     * Get the "zipCode" attribute value
     * @return the attribute value
     */
	public String getZipCode() {
        return this.zipCode;
    }

    /**
     * Set the "city" attribute value (restricted visibility)
     * @param city
     */
	void setCity( String city ) {
        this.city = city ;
    }
    /**
     * Get the "city" attribute value
     * @return the attribute value
     */
	public String getCity() {
        return this.city;
    }

    /**
     * Set the "state" attribute value (restricted visibility)
     * @param state
     */
	void setState( String state ) {
        this.state = state ;
    }
    /**
     * Get the "state" attribute value
     * @return the attribute value
     */
	public String getState() {
        return this.state;
    }

    /**
     * Set the "customerId" attribute value (restricted visibility)
     * @param customerId
     */
	void setCustomerId( Integer customerId ) {
        this.customerId = customerId ;
    }
    /**
     * Get the "customerId" attribute value
     * @return the attribute value
     */
	public Integer getCustomerId() {
        return this.customerId;
    }




	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(street);
        sb.append("|");
        sb.append(complement);
        sb.append("|");
        sb.append(zipCode);
        sb.append("|");
        sb.append(city);
        sb.append("|");
        sb.append(state);
        sb.append("|");
        sb.append(customerId);
        return sb.toString(); 
    } 

}
