/*
 * Generated by Telosys ( https://www.telosys.org/ )
 * 2022-03-31 (18:10:46)
 */
package org.demo.orders.domain.model;

import java.io.Serializable;


/**
 * Composite primary key for entity "Foo"
 *
 * @author Telosys
 *
 */
public class FooId implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY KEY ATTRIBUTES 
    private final String     code ;
    
    private final Integer    id ;
    

    /**
     * Constructor with values
     * @param code 
     * @param id 
     */
    public FooId( String code, Integer id ) {
        super();
		// TODO : check not null
        this.code = code ;
        this.id = id ;
    }
    
    //--- GETTERS & SETTERS FOR KEY FIELDS

    public String getCode() {
        return this.code;
    }


    public Integer getId() {
        return this.id;
    }


    //--- equals METHOD
	@Override
	public boolean equals(Object obj) { 
		if ( this == obj ) return true ; 
		if ( obj == null ) return false ;
		if ( this.getClass() != obj.getClass() ) return false ; 
		FooId other = (FooId) obj; 
		//--- Attribute code
		if ( code == null ) { 
			if ( other.code != null ) 
				return false ; 
		} else if ( ! code.equals(other.code) ) 
			return false ; 
		//--- Attribute id
		if ( id == null ) { 
			if ( other.id != null ) 
				return false ; 
		} else if ( ! id.equals(other.id) ) 
			return false ; 
		return true; 
	} 

    //--- hashCode METHOD
	@Override
	public int hashCode() { 
		final int prime = 31; 
		int result = 1; 
		
		//--- Attribute code
		result = prime * result + ((code == null) ? 0 : code.hashCode() ) ; 
		//--- Attribute id
		result = prime * result + ((id == null) ? 0 : id.hashCode() ) ; 
		
		return result; 
	} 

    //--- toString METHOD
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(code);
        sb.append("|");
        sb.append(id);
        return sb.toString(); 
    } 

}