/*
 * Generated by Telosys ( https://www.telosys.org/ )
 * 2022-03-31 (18:10:46)
 */
package org.demo.orders.domain.model;

import java.time.LocalDate;
import java.util.List;
import org.demo.orders.domain.common.AggregateRoot;

/**
 * Domain parent abstract class for entity "Order"
 *
 * @author Telosys
 *
 */
public abstract class OrderParent extends AggregateRoot {

	private Integer orderNo;
	private LocalDate orderDate;
	private short status;
	private String comment;
	private Integer customerId;


    private List<OrderItem> items ;

    private DeliveryAddress deliveryAddress ;

	/**
	 * Default constructor with restricted visibility
	 * (supposed to be used only by descendant )
	 */
	OrderParent() {
	}




    /**
     * Set the "orderNo" attribute value (restricted visibility)
     * @param orderNo
     */
	void setOrderNo( Integer orderNo ) {
        this.orderNo = orderNo ;
    }
    /**
     * Get the "orderNo" attribute value
     * @return the attribute value
     */
	public Integer getOrderNo() {
        return this.orderNo;
    }

    /**
     * Set the "orderDate" attribute value (restricted visibility)
     * @param orderDate
     */
	void setOrderDate( LocalDate orderDate ) {
        this.orderDate = orderDate ;
    }
    /**
     * Get the "orderDate" attribute value
     * @return the attribute value
     */
	public LocalDate getOrderDate() {
        return this.orderDate;
    }

    /**
     * Set the "status" attribute value (restricted visibility)
     * @param status
     */
	void setStatus( short status ) {
        this.status = status ;
    }
    /**
     * Get the "status" attribute value
     * @return the attribute value
     */
	public short getStatus() {
        return this.status;
    }

    /**
     * Set the "comment" attribute value (restricted visibility)
     * @param comment
     */
	void setComment( String comment ) {
        this.comment = comment ;
    }
    /**
     * Get the "comment" attribute value
     * @return the attribute value
     */
	public String getComment() {
        return this.comment;
    }

    /**
     * Set the "customerId" attribute value (restricted visibility)
     * @param customerId
     */
	void setCustomerId( Integer customerId ) {
        this.customerId = customerId ;
    }
    /**
     * Get the "customerId" attribute value
     * @return the attribute value
     */
	public Integer getCustomerId() {
        return this.customerId;
    }



    //--- GETTERS FOR LINKS
    public List<OrderItem> getItems() {
        return this.items;
    } 

    public DeliveryAddress getDeliveryAddress() {
        return this.deliveryAddress;
    } 


	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(orderNo);
        sb.append("|");
        sb.append(orderDate);
        sb.append("|");
        sb.append(status);
        sb.append("|");
        sb.append(comment);
        sb.append("|");
        sb.append(customerId);
        return sb.toString(); 
    } 

}
