/*
 * Generated by Telosys ( https://www.telosys.org/ )
 * 2022-03-31 (18:10:46)
 */
package org.demo.orders.domain.model;

import java.math.BigDecimal;
import org.demo.orders.domain.common.Entity;

/**
 * Domain parent abstract class for entity "OrderItem"
 *
 * @author Telosys
 *
 */
public abstract class OrderItemParent extends Entity {

	private long id;
	private Integer orderNo;
	private String productCode;
	private BigDecimal quantity;
	private BigDecimal unitPrice;
	private BigDecimal discount;
	private String comment;


	/**
	 * Default constructor with restricted visibility
	 * (supposed to be used only by descendant )
	 */
	OrderItemParent() {
	}




    /**
     * Set the "id" attribute value (restricted visibility)
     * @param id
     */
	void setId( long id ) {
        this.id = id ;
    }
    /**
     * Get the "id" attribute value
     * @return the attribute value
     */
	public long getId() {
        return this.id;
    }

    /**
     * Set the "orderNo" attribute value (restricted visibility)
     * @param orderNo
     */
	void setOrderNo( Integer orderNo ) {
        this.orderNo = orderNo ;
    }
    /**
     * Get the "orderNo" attribute value
     * @return the attribute value
     */
	public Integer getOrderNo() {
        return this.orderNo;
    }

    /**
     * Set the "productCode" attribute value (restricted visibility)
     * @param productCode
     */
	void setProductCode( String productCode ) {
        this.productCode = productCode ;
    }
    /**
     * Get the "productCode" attribute value
     * @return the attribute value
     */
	public String getProductCode() {
        return this.productCode;
    }

    /**
     * Set the "quantity" attribute value (restricted visibility)
     * @param quantity
     */
	void setQuantity( BigDecimal quantity ) {
        this.quantity = quantity ;
    }
    /**
     * Get the "quantity" attribute value
     * @return the attribute value
     */
	public BigDecimal getQuantity() {
        return this.quantity;
    }

    /**
     * Set the "unitPrice" attribute value (restricted visibility)
     * @param unitPrice
     */
	void setUnitPrice( BigDecimal unitPrice ) {
        this.unitPrice = unitPrice ;
    }
    /**
     * Get the "unitPrice" attribute value
     * @return the attribute value
     */
	public BigDecimal getUnitPrice() {
        return this.unitPrice;
    }

    /**
     * Set the "discount" attribute value (restricted visibility)
     * @param discount
     */
	void setDiscount( BigDecimal discount ) {
        this.discount = discount ;
    }
    /**
     * Get the "discount" attribute value
     * @return the attribute value
     */
	public BigDecimal getDiscount() {
        return this.discount;
    }

    /**
     * Set the "comment" attribute value (restricted visibility)
     * @param comment
     */
	void setComment( String comment ) {
        this.comment = comment ;
    }
    /**
     * Get the "comment" attribute value
     * @return the attribute value
     */
	public String getComment() {
        return this.comment;
    }




	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(orderNo);
        sb.append("|");
        sb.append(productCode);
        sb.append("|");
        sb.append(quantity);
        sb.append("|");
        sb.append(unitPrice);
        sb.append("|");
        sb.append(discount);
        sb.append("|");
        sb.append(comment);
        return sb.toString(); 
    } 

}
