/*
 * Generated by Telosys ( https://www.telosys.org/ )
 * 2022-03-31 (18:10:46)
 */
package org.demo.orders.domain.repository;

import java.util.List;

import org.demo.orders.domain.common.AggregateRootRepository;

import org.demo.orders.domain.model.Aaa;

public interface AaaRepository extends AggregateRootRepository<Aaa, Integer> {

	// Add here any specific methods if necessary 'findByXxx' et 'countByXxxx' 
/*
	Examples :
	
	List<Aaa> findByXxx(Integer xxx);


	long countByXxx(Integer xxx);
*/
}
