/*
 * Generated by Telosys ( https://www.telosys.org/ )
 * 2022-03-31 (18:10:46)
 */
package org.demo.orders.domain.repository;

import java.util.List;

import org.demo.orders.domain.common.AggregateRootRepository;

import org.demo.orders.domain.model.Foo;
import org.demo.orders.domain.model.FooId;

public interface FooRepository extends AggregateRootRepository<Foo, FooId> {

	// Add here any specific methods if necessary 'findByXxx' et 'countByXxxx' 
/*
	Examples :
	
	List<Foo> findByXxx(Integer xxx);


	long countByXxx(Integer xxx);
*/
}
