/*
 * Generated by Telosys ( https://www.telosys.org/ )
 * 2022-04-01 (00:02:09)
 */
package org.demo.orders.application.service.impl;

import java.util.List;
import java.util.Optional;
import javax.inject.Inject;
import org.springframework.stereotype.Component;

import org.demo.orders.rest.dto.response.FooRestResponse;
import org.demo.orders.domain.model.Foo;
import org.demo.orders.domain.model.FooId;
import org.demo.orders.domain.repository.FooRepository;
import org.demo.orders.application.mapper.FooMapper;
import org.demo.orders.rest.dto.FooRestDto;

/**
 * Service for "QUERIES" (database read operations)
 * Entity Foo
 *
 * @author Telosys
 */
@Component
public class FooQueryService {

	@Inject
	private FooRepository fooRepository;
	
	@Inject
	private FooMapper fooMapper;

	private FooId buildId(String code, Integer id) {
		return new FooId(code, id);
	}
	
	/**
	 * Get and return a Foo instance for the given id
	 * @param code id
	 * @param id id
	 * @return entity found (or null if not found)
	 */
	public FooRestDto getFoo(String code, Integer id) {
		Optional<Foo> foo = fooRepository.findById(buildId(code, id));
		if (foo.isPresent()) {
			return fooMapper.toDTO(foo.get());
		}
		else {
			return null;
		}
	}
	
	/**
	 * Get a page of Foo 
	 * @param page page number (from 1 to N)
	 * @param size page size
	 * @param sort
	 * @param order
	 * @return
	 */
	 public FooRestResponse findFoo(Integer page, Integer size, String sort, String order) {

		// Find all in database
		List<Foo> fooList = fooRepository.findAll(page-1, size, sort, order);

		// Count all in database
		long totalElements = fooRepository.count();
		
		// Build API response object
		//return buildResponse(fooList, totalElements, size);
		List<FooRestDto> list = fooMapper.toDTOList(fooList);
		return new FooRestResponse(list, totalElements, size);

	}


}
