/*
 * Generated by Telosys ( https://www.telosys.org/ )
 * 2022-03-31 (18:10:46)
 */
package org.demo.orders.domain.common;

/**
 * Ancestor for all domain model entities
 *
 * @author Telosys
 *
 */
public abstract class Entity {

}